### ISSUE TITLE
what are some recommendations for feature engineering?

### ISSUE THREAD

**Issue by ddgg** [Yizhan-Oliver-Shu/jump-models#2]
hi, I tried to run the example code for kas-usd from 2022-06-01/2024-10-07, and it's largely one-direcitonal trend, it just split in the middle, maybe two volatility regime? I was expecting switches between smaller fluctuating up/downs, do you have some recommendations regarding tuning or feature engineering? thank you for the good work

![2024-10-08-115035_2560x1600_scrot](https://github.com/user-attachments/assets/c3c5c0fc-694a-445e-afe8-45cf47573f0f)
![2024-10-08-114948_2560x1600_scrot](https://github.com/user-attachments/assets/b7a49c6e-d0f8-4047-8e73-edfedd704d9a)

**Comment by Yizhan-Oliver-Shu** [comment]
Hello, thank you for sharing your interesting example. I’ll aim to provide my thoughts within the next few days.

**Comment by Yizhan-Oliver-Shu** [comment]
Hello, apologies for the delay. I have made an effort to respond promptly. 

1. The curve primarily trends upward without any significant drawdowns. While I manually labeled “bull/bear” regimes, for your case, it would be more appropriate to interpret these as “super/normal” periods. This is particularly evident when $\lambda=0$: the extended red periods mostly remain flat (one exception of a drawdown around 2022/10), so they are not bearish.

2. If the regime shifts are too infrequent with $\lambda=50$ and you seek more transitions, reducing $\lambda$ (e.g., to around 10) is the simplest adjustment. However, if you’re not satisfied with the fit when $\lambda=0$, i.e. the “super/normal” differentiation doesn’t meet your needs, you may need to consider a different set of features. 

3. The features you use should reflect what you prioritize in defining regimes. My default set includes two return features (return and Sortino ratio) and one volatility measure, which naturally emphasizes return characteristics. As a result, periods of exceptionally high returns form a distinct regime. If you prefer to avoid this, you might consider removing one of the return measures, such as retaining only the Sortino ratio. Alternatively, if other metrics, like technical indicators (e.g., RSI, %K), are relevant to your case, adding them is certainly an option. 

4. Adjusting halflives to lower values (e.g., [5, 10, 21]) can also encourage more frequent regime shifts. 

Ultimately, it depends on what aspects of regimes you want to emphasize. You would have an idea of what the regime fitting captures under $\lambda=0$, and increasing $\lambda$ would encourage persistence but won’t significantly change the general regime shape (ignoring temporal persistence).

**Comment by ddgg** [comment]
thank you for the explanation,  I'll follow your advice and try something else

**Comment by ddgg** [comment]
thank you for the explanation, I'll follow your advice and try something new indicators
